mysql:
  image: mysql:5.7
  ports:
   - "3306"
  volumes:
   - /Users/rkanakam/Servers/neu/mysql/data:/var/lib/mysql
   - /Users/rkanakam/Servers/neu/mysql/initdb:/docker-entrypoint-initdb.d
  environment:
   - MYSQL_ROOT_PASSWORD=liferay  
  stdin_open: true
  tty: true
  
elasticsearch:
  image: elasticsearch:2.2.0
  ports:
   - "9200"
   - "9300"
  volumes:
   - /Users/rkanakam/Servers/neu/elasticsearch/data:/usr/share/elasticsearch/data
  environment:
   - cluster.name=Elasticsearch_Docker
   - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  stdin_open: true
  tty: true
   
liferay-dxp:
  build: /Users/rkanakam/Library/docker-workspace/liferay-dxp-sp2
#  image: rkanakam/liferay-dxp-sp2
  ports:
   - "9080:8080"
  volumes:
   - /Users/rkanakam/Servers/neu/app/data:/opt/liferay-dxp-digital-enterprise-7.0-sp2/data
   - /Users/rkanakam/Servers/neu/app/deploy:/opt/liferay-dxp-digital-enterprise-7.0-sp2/deploy
  links:
   - mysql
   - elasticsearch   
  stdin_open: true
  tty: true 