oracle-xe:
 image: sath89/oracle-xe-11g
 ports:
  - "1521"
  - "8080"
 volumes:
  - $PWD/oracle-xe/data:/u01/app/oracle
  - $PWD/oracle-xe/initdb:/docker-entrypoint-initdb.d
 stdin_open: true
 tty: true

mysql:
 image: mysql:5.7
 ports:
  - "3306"
 volumes:
  - $PWD/mysql/data:/var/lib/mysql
  - $PWD/mysql/initdb:/docker-entrypoint-initdb.d
 environment:
  - MYSQL_ROOT_PASSWORD=liferay  
 stdin_open: true
 tty: true
  
elasticsearch:
  image: elasticsearch:2.2.0
  ports:
   - "9200"
   - "9300"
  volumes:
   - $PWD/elasticsearch/data:/usr/share/elasticsearch/data
  environment:
   - cluster.name=Elasticsearch_Docker
   - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  stdin_open: true
  tty: true
   
liferay-dxp:
#  container_name: liferay-dxp-sp2-neu  
  build: $PWD
  ports:
   - "8080"
   - "13333"
   - "8000"   
  volumes:
   - $PWD/app/data:/opt/liferay-dxp-digital-enterprise-7.0-sp2/data
   - $PWD/app/deploy:/opt/liferay-dxp-digital-enterprise-7.0-sp2/deploy
  links:
   - oracle-xe
   - mysql
   - elasticsearch   
  stdin_open: true
  tty: true 